### ISSUE TITLE
Verify tutorials (relates #508)

### ISSUE THREAD

**Issue by Stasik0** [open62541/open62541#509] opened 2016-01-14 20:48 UTC
Before freezing 0.2 we need to make sure tutorials are aligned with current api

**Comment by ichrispa** [comment] 2016-01-15 18:01
Hmmm... I have two "volunteers" that can be assigned this task (with ETA mid february). Would that be sufficient?

**Comment by Stasik0** [comment] 2016-01-15 18:14
Yea,  but first we need to be sure that the api is stable

**Comment by Pro** [comment] 2016-01-21 20:38
See also: PR https://github.com/open62541/open62541/pull/516
I'll go through the tutorials and try to fix any errors when I see them using the current version.

**Comment by Stasik0** [comment] 2016-01-21 20:59
Can we actually include .c files in sphinx? Kinda, "include xyz.c:3-15"? Would be much better than double maintenence.

**Comment by jpfr** [comment] 2016-01-22 11:17
Totally.
Maybe we can write large parts of the documentation as comments in tutorial c-files and in the public header files. You know, take the code, detect comments in `/** */` double-star comments and wrap everything else in code blocks.

Otherwise we will run into impedence mismatches between code and docs. At least between releases.

**Comment by Stasik0** [comment] 2016-01-26 21:38
isn't there some sphinx solution?

**Comment by FlorianPalm** [comment] 2016-01-27 07:15
We would also need Doxygen, wouldn't we?  [Look here](http://stackoverflow.com/questions/11246637/using-sphinx-apidoc-to-generate-documentation-from-c-code)

**Comment by Stasik0** [comment] 2016-01-27 08:00
I thought about "including" parts of source code into tutorial articles which is, imho, not doxygen anymore.

**Comment by memaikey** [comment] 2016-06-17 15:13
First steps with open62541-client tutorial doesn't compile.
(trying to upload fix, but new to git)

**Comment by memaikey** [comment] 2016-06-20 09:49
Tutorial "Adding nodes to a server and connecting nodes to user-defined values" mentions 3 cases under  "Variants", but only lists 2.

**Comment by Stasik0** [comment] 2016-06-20 10:16
@memaikey its even worth: the listed items do not match the values in the struct: the truth is in the code: https://github.com/open62541/open62541/blob/38d4e7fbad8d11826521cecda630046ffa20035d/include/ua_types.h#L535

**Comment by Stasik0** [comment] 2016-06-23 11:00
@memaikey did you check all the tutorials?

**Comment by memaikey** [comment] 2016-06-23 11:23
@Stasik0 I finished toturial 1&2 and just made a pull request for my latest updates. I've read tutorial 3&4, but they basically say "go look at the code". I am currently testing these two. I don't think I'll check the final tutorial in a while.

**Comment by schmidmaxa** [comment] 2016-06-30 04:34
I've checked up to "Creating Object Instances".. I can't get that one to compile, but I'm sure the issue is on my end getting the correct headers. Still new to much of this, so the documentation might be a little light on that one for a newbie like myself.

**Comment by markusgraube** [comment] 2016-07-14 19:27
@Stasik0 Sphinx support including parts of the source files:

```
.. literalinclude:: ../../examples/server_firstSteps.c
   :language: c
   :lines: 1,3,5-10,20-
```

However, current files in examples are not the same as in the tutorials.

**Comment by jpfr** [comment] 2017-04-24 12:15
Tutorials were refactored and are now included in example .c files.

**Closed by jpfr** 2017-04-24 12:15 UTC
Labels: 0.2
