### ISSUE TITLE
Badtimeout

### ISSUE THREAD

**Issue by ruikai** [open62541/open62541#988] opened 2017-03-13 05:33 UTC
Description
===========
the server run in the cortex-a8 is ok;
but run in the cortex-a5,shows that :BadTimeout ;

Background Information / Reproduction Steps
===========================================

See here for the kinds of information we need to reproduce the bug and how to obtain it:
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): server
 - [ ] Operating system: linux arm cortex-a8 ,cortex-a5;
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment] 2017-03-13 08:26
Duplicate of #987

**Closed by jpfr** 2017-03-13 08:26 UTC
