### ISSUE TITLE
Not able to build the OPC UA server on raspberry pi as per the documentation , please give the correct and updated steps to build opc UA server on raspberry pi ....

### ISSUE THREAD

**Issue by Ganesh-mali** [open62541/open62541#3267] opened 2019-11-12 08:41 UTC
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment] 2019-11-12 08:46
I just built open62541 on my Raspberry Pi yesterday.

Since you did not fill out any requested info at all in the issue template, and you did not give us any error message what's going wrong, I close this issue as invalid.

We are not able to help you with this little information.

Read https://stackoverflow.com/help/minimal-reproducible-example first and then open a new issue with all the requested information!

**Closed by Pro** 2019-11-12 08:46 UTC
