### ISSUE TITLE
Help needed to connect Unified Automation demo server with open62541 client

### ISSUE THREAD

**Issue by crazyblack4** [open62541/open62541#1818] opened 2018-05-30 08:25 UTC
Hi all,
Im beginner for opcua. Trying to connect Unified Automation demo server with open62541 simple client.
I tried anonymous and username/password. i can able to connect anonymous but not with username/password getting below error,

`error/client       No suitable UserTokenPolicy found for the possible endpoints`

> **Server Configuration:**
> Server                       :  OPC UA C++ Demo Server V1.5.6 (Windows)
> Security                    :  None
> Anonymous             :  Enabled
> Username/Passwd   :  Enabled

**Used client code**
```
#include <stdio.h>
#include "open62541.h"

int main(int argc, char *argv[])
{
    /* Create a client and connect */
    UA_Client *client = UA_Client_new(UA_ClientConfig_default);
    //UA_StatusCode status = UA_Client_connect(client, "opc.tcp://localhost:48010");
    UA_StatusCode status = UA_Client_connect_username(client, "opc.tcp://localhost:48010","john","master");

    if(status != UA_STATUSCODE_GOOD) {
        UA_Client_delete(client);
        return status;
    }
   printf("\nConnected\n");
   UA_Client_delete(client); /* Disconnects the client internally */
    return status;
}

```

Please advise is it normal or what things need to be done to connect with other server.
Thanks in advance !

Checklist
=========
 - open62541 Version (release number or git tag): **Current master**
 - Other OPC UA SDKs used (client or server): **OPC UA C++ Demo Server V1.5.6 (Windows)**
 - Operating system:**Ubuntu**

**Comment by jpfr** [comment] 2018-05-31 16:41
Some servers require to encrypt the username/password even when the SecureChannel does not use encryption. This seems to be the case here.

Try to use a SecurityPolicy with encryption. That should work.

Closed as a duplicate of #934.
Please reopen if required.

**Closed by jpfr** 2018-05-31 16:41 UTC
