### ISSUE TITLE
Not able to compile XML nodeset

### ISSUE THREAD

**Issue by santoshpanda1989** [open62541/open62541#1106] opened 2017-07-07 19:56 UTC
HI,
I am trying to compile my own XML file. I tried with cmake and then tried to compile the nodeset.c, open62541.c, and myServer.c but I am getting error while compiling it. Please find below the command.
gcc -std=c99 myServer.c nodeset.c open62541.c -o myServer

I have attached the screenshot of the error.

Thanks,
Santosh
![error](https://user-images.githubusercontent.com/19244975/27974629-1c8179d8-635f-11e7-8148-e0099c887ade.png)

**Comment by jpfr** [comment] 2017-07-08 12:25
@ichrispa That's a nodeset compiler issue.
Can you have a look?

**Comment by santoshpanda1989** [comment] 2017-07-10 10:29
Hi,
Is there any update?

Thanks,
Santosh

**Comment by XB32Z** [comment] 2017-07-10 12:50
Hi, 
I had this issue, it's the cmake that wasn't updated since v0.2 and that doesn't work with the master. I made a (issue already)[https://github.com/open62541/open62541/issues/1103]

**Comment by Pro** [comment] 2017-08-13 10:16
duplicate of #1103

**Closed by Pro** 2017-08-13 10:16 UTC
Labels: namespace-compiler

**Comment by merlingeorge555** [comment] 2018-05-20 07:54
Hi @santoshpanda1989 Can you teach me how to work on XML node set compiler?

**Comment by merlingeorge555** [comment] 2018-05-20 08:30
@santoshpanda1989  Thank you for your immediate response. Let me say my requirement.  
I have a XML file in standard NS0. 
Via cmake I should a create a .h and .c file and it should it produce a example server file. Is that possible? If you find the exact steps, Kindly share with me
