### ISSUE TITLE
C++ library for open62541

### ISSUE THREAD

**Issue by yurybura** [open62541/open62541#2067] opened 2018-09-18 09:57 UTC
Description
===========
What about provide 'official' C++11/14/17 library for open62541 on operating systems such as Linux and Windows?

Background Information / Reproduction Steps
===========================================
C++ has a lot idioms that simplified development such as RAII, containers, shared pointers, etc.

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Windows, Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment] 2018-09-18 11:19
Duplicate of #1768 

It's always nice to have modern programming languages. Since our stack has a high focus on portability and support of different compilers and also microcontroller architectures, not all of these special compilers support new features, some even do not support C++.
That is the reason why this stack is mainly in written in C99.

We are currently focussing on implementing still missing features for the full OPC UA specification, thus there is not much time for other nice-to-have features like an official C++ library.

You can check out this repo:
https://github.com/bazza2jw/open62541Cpp

It implements a C++ wrapper around the C code. That repo is not (yet) officially supported by the open62541 core devs, but we would be really happy if we can bring it at some point under the hood of open62541. Thus feel free to collaborate and write PRs for @bazza2jw's repo.

**Closed by Pro** 2018-09-18 11:19 UTC
