### ISSUE TITLE
SERVER CONFIG setCustomHostname NOT WORKING

### ISSUE THREAD

**Issue by Fabrizio997** [open62541/open62541#5159] opened 2022-05-30 18:32 UTC
## Description

I'm trying to set a custom port and hostname for a simple server, but when I add the code with the function for the hostname it doesn't work.
Here is my simple server code modified:

    int main(int argc, char * argv[]){
        signal(SIGINT, stopHandler);
        signal(SIGTERM, stopHandler);

        UA_Server *server = UA_Server_new();
    
        if (argc > 2){
    	    UA_Int16 port_number = atoi (argv[2]);
    	    UA_ServerConfig_setMinimal(UA_Server_getConfig(server), port_number, 0);
        }
        if (argc > 1){
    	    UA_String hname;
    	    UA_String_init(&hname);
        	hname.length = strlen(argv[1]);
        	hname.data = (UA_Byte *) argv[1];
    	    UA_ServerConfig_setCustomHostname(UA_Server_getConfig(server),hname);
    }
    
    else
    UA_ServerConfig_setDefault(UA_Server_getConfig(server));

    UA_StatusCode retval = UA_Server_run(server, &running);

    UA_Server_delete(server);
    return retval == UA_STATUSCODE_GOOD ? EXIT_SUCCESS : EXIT_FAILURE;
    }

error I get on compiling:

    myServer.c: In function ‘main’:
    myServer.c:28:9: warning: implicit declaration of function ‘UA_ServerConfig_setCustomHostname’ [-Wimplicit-function-        declaration]
       28 |         UA_ServerConfig_setCustomHostname(UA_Server_getConfig(server),hname);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/bin/ld: /tmp/ccCSgUWy.o: in function `main':
    myServer.c:(.text+0x290): undefined reference to `UA_ServerConfig_setCustomHostname'
    collect2: error: ld returned 1 exit status
    ## Background Information / Reproduction Steps

Used CMake options:

cmake -DBUILD_SHARED_LIBS=ON -DUA_ENABLE_AMALGAMATION=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL ..

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):[fbc3977](https://github.com/open62541/open62541/commit/fbc3977c069ca69083a3812be5a887056686b818)
[8](https://github.com/open62541/open62541/commit/fbc3977c069ca69083a3812be5a887056686b818)
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 22.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by neojaw** [comment] 2022-05-31 05:13
Duplicate of #5132?

**Closed** 2022-06-07 22:17 UTC
