### ISSUE TITLE
connect to node-opcua from open62541 fails due to encrypted username/password

### ISSUE THREAD

**Issue by bnadem** [open62541/open62541#1488] opened 2018-01-04 16:50 UTC
I'm trying to make a connection from the open62541 client to the node-opcua Server, "hello and getendpoint works fine, but if you're  using the user and password (ua_client_username), i l get the message  error "No suitable usertockePolicy found the possibel endpoints",  with node-opcua client or with UAeXPERT in work fine, but  not with the open62541!

**Comment by jpfr** [comment] 2018-01-05 16:53
Hey @bnadem ,

It is possible that node-opcua uses encryption for username/password even if the SecureChannel is not encrypted.

Can you prepare a network dump with Wireshark?
It's reasonably easy to do. And we need the details to resolve the issue.

Thanks.

**Comment by erossignon** [comment] 2018-01-05 17:58
@jpfr , I confirm that node-opcua encrypts the UserIdentityToken if secure channel is not encrypted as required by the specs:
Release 1.03 26 OPC Unified Architecture, Part 4 :

> The ActivateSession Service is used to associate a user identity with a Session. When a Client provides a user identity then it shall provide proof that it is authorized to use that user identity. The exact mechanism used to provide this proof depends on the type of the UserIdentityToken. If the token is a UserNameIdentityToken then the proof is the password that is included in the token. If the token is an X509IdentityToken then the proof is a signature generated with private key associated with the Certificate. The data to sign is created by appending the last serverNonce to the serverCertificate specified in the CreateSession response. **If a token includes a secret then it should be encrypted using the public key from the serverCertificate.** 

This takes place around [here](https://github.com/node-opcua/node-opcua/blob/9e7b4a8f293a4144defb528674fe6f3c8125f798/packages/node-opcua-server/src/opcua_server.js#L983)

Let me know if you agree with this behavior or if we've missed something in interpreting the specs.

**Comment by jpfr** [comment] 2018-01-05 19:54
Hey @erossignon ,

Your side is correct. We implement encryption in PR #1282.
Decoding username/password will be implemented afterwards.

We will have to wait until then.

**Comment by bnadem** [comment] 2018-01-08 09:09
here is twork dump with Wireshark,  i hope it helpfull

**Comment by bnadem** [comment] 2018-01-08 09:16
Hey @jpfr node 
here is my network dump with Wireshark, 
[username_pcapng.txt](https://github.com/open62541/open62541/files/1611028/username_pcapng.txt)

**Comment by Pro** [comment] 2018-02-01 14:52
Closing in favour of #1539

**Closed by Pro** 2018-02-01 14:52 UTC
Labels: encryption

**Comment by Pro** [comment] 2018-02-01 15:33
Also duplicate of #934
