### ISSUE TITLE
manuallySendPublishRequest variable duration time

### ISSUE THREAD

**Issue by Aleskey78** [open62541/open62541#550] opened 2016-02-29 16:20 UTC
Hello,

I've written a small console application that calls a UA_Client_Subscriptions_manuallySendPublishRequest function each 100ms with the following parameters:
        UA_SubscriptionSettings settings = UA_SubscriptionSettings_standard;
        settings.requestedPublishingInterval = 0.0;
        settings.requestedMaxKeepAliveCount = 10;
        settings.requestedLifetimeCount  = settings.requestedMaxKeepAliveCount * 3;
        settings.maxNotificationsPerPublish = 1024;

At the beginning the duration of a call is about  900ms.
And now the gag: if I hold for a while (3 secs) a scrollbar of the console with a debug output -> the function takes only ca. 5ms for a PublishRequest/Response!

A Wireshark dump is attached.

Thanks
[publishReqResTime.zip](https://github.com/open62541/open62541/files/151281/publishReqResTime.zip)

**Comment by Aleskey78** [comment] 2016-03-01 09:47
Actually it’s the same if you’ll try to step through the UA_Client_Subscriptions_manuallySendPublishRequest in debug mode.

**Comment by jpfr** [comment] 2016-03-04 09:13
bump @ichrispa 
That looks like a blocker for 0.2 in the subscriptions.

**Comment by Stasik0** [comment] 2016-03-04 09:40
can it be some timing issue, since the program is paused during debug or "scrolling"?

**Comment by Aleskey78** [comment] 2016-03-04 12:42
This “scrolling” has however no effect on Read/Write operations that I had to use as workaround for polling.

**Comment by ichrispa** [comment] 2016-04-05 22:50
Is there a reproducable test case? I still use subscriptions daily and have not noticed this behavior before.

**Comment by jpfr** [comment] 2016-05-09 10:18
Hey @Aleskey78 ,

the subscriptions part was refactored. It should work fine now.

For subscriptions, the server may delay an answer depending on whether data changes and the maximum keepalive frequency. In the standard settings (UA_SubscriptionSettings_standard) for our client, the server always tries to send a publish response right away with either a datachangenotification or a keepalive.

Can you check with master after commit e4ff940 and tell us if we can close the issue?

**Comment by Aleskey78** [comment] 2016-05-13 20:00
Hi @jpfr,

I've just tested 768b261 and it's showing same issue with my settings:
```
        UA_SubscriptionSettings settings = UA_SubscriptionSettings_standard;
        settings.requestedPublishingInterval = 0.0;
        settings.requestedMaxKeepAliveCount = 10;
        settings.requestedLifetimeCount  = settings.requestedMaxKeepAliveCount * 3;
        settings.maxNotificationsPerPublish = 1024;
```

**Comment by Aleskey78** [comment] 2016-05-13 20:16
@jpfr,

just tested a little bit more :) and it seems that the issue is solved.
So after holding a scroolbar for a 3 - 5 seconds 'UA_Client_Subscriptions_manuallySendPublishRequest' function takes less than a 3ms (it was about 900ms at the beginning). BUT it still receives notifications and after the first one the duration of a call goes back to 900ms.
It looks a bit strange for me, but it works :)

**Closed** 2016-06-06 09:36 UTC
Labels: 0.2
