### ISSUE TITLE
CTT Problem

### ISSUE THREAD

**Issue by jhj0955** [open62541/open62541#1926] opened 2018-07-18 05:52 UTC
open62541 Version (release number or git tag):
Git-Revision: 0.3-rc2-217-g0afd439a

There was a problem running the ctt 
It is similar to issues1913 (subscription )
![image](https://user-images.githubusercontent.com/28384271/42862381-38cfe300-8a9a-11e8-850c-1f70d9f15355.png)

What needs to be corrected to fix this part?
I would really appreciate if you answer about this shortly.
Thank you.

project setting's open62541-ctt-master by https://github.com/open62541/open62541-ctt

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: 
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment] 2018-07-18 07:38
Duplicate of 1913

**Closed by jpfr** 2018-07-18 07:38 UTC
