### ISSUE TITLE
 server crash Multiple client from same machine to single Server (Freertos_LWIP_stm)

### ISSUE THREAD

**Issue by embbo** [open62541/open62541#2700] opened 2019-05-02 12:39 UTC
Hallo, 
I am facing a problem while connecting the two client from same laptop. 
1. I have open62541 Cleint
2. UaExpert cleint .
when I try to connect both client(in same laptop) with embedded server it fails to connect and server crashes too (have to restart server).

**Comment by Pro** [comment] 2019-05-02 13:09
Sorry, but I have to close this issue, since you did not fill out the issue template.

There is not enough information in your description to guess what could be wrong.
E.g., which version are you using, what is the error message, did you try to use gdb to find the cause of the crash, how can we reproduce the issue, ...

**Closed by Pro** 2019-05-02 13:09 UTC
