### ISSUE TITLE
Node deletion

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#345] opened 2015-08-25 22:01 UTC
@ichrispa
You wrote the service for node deletion in the hl abstraction branch. That's looking good in general.
In addition to the existing code, we should think about necessary conditions for deletion and intermediate states of the information model.
- Nodes can only be deleted if there are no hierarchical references downwards from them. This rule is not written in a the standard. But it seems to cover most inconsistencies I could think of.
- We don't have real transactions for the information model. So somebody could add a reference at the same time we try to remove the node. However, we can control that the right node version (with no outgoing hierarchical references) is current upon deletion. For that, we need to change the node store API.

Is that ok with you?

**Comment by ichrispa** [comment] 2015-08-25 22:31
hey @jpfr,

yes, I agree on both counts. I would however plead for not having any nodestore userspace functions changing semantics or structure.

I found a comment at some point that questioned if hierachical deletions are an acceptable solution. Should something like that even be considered?

Best regads,

ichrispa

**Comment by Stasik0** [comment] 2016-02-09 13:06
bump

**Comment by Pro** [comment] 2018-02-01 15:05
@jpfr isn't this already implemented in current master?
Ok to close?

**Comment by Pro** [comment] 2018-11-06 09:50
Related/duplicate of #1812 and #1730

**Comment by Pro** [comment] 2019-09-03 14:49
The node store API was changed a lot since this issue was opened and is most likely fixed. If not, please open a new issue.

**Closed by Pro** 2019-09-03 14:49 UTC
