### ISSUE TITLE
open62541 vs Indusoft Web Studio interoperability issue

### ISSUE THREAD

**Issue by adliner** [open62541/open62541#1224] opened 2017-09-20 20:47 UTC
Hi,
I tried using open62541 sample server codes with Indusoft Web studio by Wonderware. Unfortunately Web studio gets frozen when trying to connect to sample server. Is it any known issue already seen with any other OPC-UA clients?

This can be easily reproduced by downloading a trial version of Indusoft Web Studio 7 or 8: http://www.indusoft.com/Products-Downloads/HMI-Software/InduSoft-Web-Studio

Then simple clicking:
![image](https://user-images.githubusercontent.com/8227441/30666413-885ba586-9e54-11e7-8c3b-c111f8643c4e.png)

I tried with latest amalgamated open62541 lib in demo project: https://github.com/adliner/OPCServerDemo but this issue also occurs with any other sample server codes.

This basically looks more like Indusoft Web Studio bug but on the other hand it works fine with other servers based on different OPC-UA stacks, so perhaps it's some open62541 standard compatibility issue.

PS: I also captured WireShark traffic dump, available at: https://github.com/adliner/OPCServerDemo/blob/master/OPC/indusoft_wireshark_dump.pcapng

**Comment by adliner** [comment] 2017-09-25 19:16
Hi,
I've been trying to investigate this issue on my own. Hence I did some network traffic analysis using Wireshark.

I compared connection between Indusoft client and:
- open62541 sample server
- OPC-UA demo server available at opc.tcp://opcua.demo-this.com:51210/UA/SampleServer


I noticed some thing. open62541 generated packet contain 'ArraySize' set to '-1'(0xffffffff) when describing null string while demo server sends packet containing just zeros (0x00000000) Just see this one below:

![image](https://user-images.githubusercontent.com/8227441/30826350-9dfb7aa2-a236-11e7-97d3-59ed4d94b970.png)


Is this expected behavior in regard of OPC-UA specification?

**Comment by jpfr** [comment] 2017-09-25 21:41
Hey @adliner ,

both are valid values in OPC UA.

-1 is an undefined string.
0 is a string of length zero.

The application should be able to deal with both.

**Comment by Stasik0** [comment] 2017-09-26 07:51
Can't we change to 0 to be "more interoperable"?

**Comment by Stasik0** [comment] 2017-09-26 08:01
@adliner: you can try to tweak the answer yourself:

https://github.com/open62541/open62541/blob/b3ad5a6c89ebb14654ea5239111ee34bffcec14f/src/server/ua_services_securechannel.c#L9

There you can adjust stringTableSize in UA_ResponseHeader? @jpfr it is size_t currently? What is the logic of sending -1?

**Comment by adliner** [comment] 2017-10-16 21:56
Hi,
I tried to experiment with the code to modify the coding of undefined strings/zero length strings but seems like it introduces regression so probably it's not conformant with the protocol's spec.

I think Indusoft might be having some problems while analyzing the structure of node Object/Server which is created by default:
![image](https://user-images.githubusercontent.com/8227441/31637113-7739050e-b2cd-11e7-8810-dabec1b15313.png)

 Is this mandatory node? Can this be skipped? Or is it required by the standard?

**Comment by jpfr** [comment] 2017-10-17 08:43
The server node is mandatory.
Many other tools rely on the content.
For example the ServerStatus to signal in imminent shutdown.

Can you provide your example to Indusoft to provide a patch?

**Comment by adliner** [comment] 2017-10-17 08:49
Yeah,
I'll try to contact Indusoft support team. It would be great if they could resolve this issue. I'll get back with their response.

**Comment by Pro** [comment] 2017-11-10 22:36
@adliner any update regarding this issue?

**Comment by adliner** [comment] 2017-11-13 10:12
I had contacted Indusoft support team and got a feed back information that the issue was filed in their internal bugs database and now the problem is under the investigation. I'll post some followup message once I get any further update from the company.

**Comment by StalderT** [comment] 2017-11-30 11:45
I installed Indusoft Web Studio 8.1 and did some tests. The problem is that the client (Indusoft) is waiting for the server to close the socket, which the server does not do. I did a workaround https://github.com/open62541/open62541/pull/1417,  @jpfr could you please look where the right place to close the socket?

Everything else seems to work well.

**Comment by StalderT** [comment] 2017-11-30 11:57
To be more precise: the server must close the socket (connection) after a CloseSecureChannelRequest

**Comment by Pro** [comment] 2017-12-01 22:32
@StalderT can you confirm (and close) that #1417 fixes this issue?

**Comment by StalderT** [comment] 2017-12-02 12:35
works for me with 8.1

@adliner can you check if latest master commit solve the issue and close the issue if it works.

**Closed** 2017-12-02 15:08 UTC
