### ISSUE TITLE
Multithreading features 

### ISSUE THREAD

**Issue by starki93** [open62541/open62541#2651] opened 2019-04-15 08:04 UTC
Good morning,

for my project i am testing the multithreading build-option with the hope it would be possible to do parallel requests. What part of the server is working in multiple threads? For me it's not possible to call a method which is running 3 seconds and read multiple times while the method is running. Subscriptions stop working if the method is running too. Did i something wrong, or did i forget some configs?

```cpp

static UA_StatusCode
helloWorldMethodCallback(UA_Server *server,
                         const UA_NodeId *sessionId, void *sessionHandle,
                         const UA_NodeId *methodId, void *methodContext,
                         const UA_NodeId *objectId, void *objectContext,
                         size_t inputSize, const UA_Variant *input,
                         size_t outputSize, UA_Variant *output) {

    std::cout << "called" << std::endl;

    auto *inputVal = (UA_Int32 *)input->data;

    std::cout << "receive method [" << std::to_string(*inputVal) << "]" << std::endl;

    UA_Variant_setScalarCopy(output, inputVal , &UA_TYPES[UA_TYPES_INT32]);

    std::cout << "wait method [" <<std::to_string(*inputVal) << "]" << std::endl;

    UA_sleep_ms(3000);

    std::cout << "finish method [" << std::to_string(*inputVal)  << "]" << std::endl;

    return UA_STATUSCODE_GOOD;
}

int main() {
    signal(SIGINT, stopHandler);
    signal(SIGTERM, stopHandler);

    UA_ServerConfig *config = UA_ServerConfig_new_default();

    config->nThreads = 25;
    UA_Server *server = UA_Server_new(config);

    addCurrentTimeDataSourceVariable(server);

    addHellWorldMethod(server);

    UA_StatusCode retval = UA_Server_run(server, &running);

    return retval == UA_STATUSCODE_GOOD ? EXIT_SUCCESS : EXIT_FAILURE;
}
```

Best regards,
Alexander

 - [x] open62541 Version (release number or git tag): master
 - [x] Other OPC UA SDKs used (client or server): no
 - [x] Operating system: ubuntu 18.04

**Comment by jpfr** [comment] 2019-04-15 11:32
Multithreading is experimental and will break in its current form.
There will be more to come in the mid-term future.
At the moment, protect with a mutex and use only one thread.

Closed as a duplicate of #2313.

**Closed by jpfr** 2019-04-15 11:32 UTC
