### ISSUE TITLE
Nested VariableType nodes

### ISSUE THREAD

**Issue by andreas-ibm** [open62541/open62541#1414] opened 2017-11-29 17:10 UTC
Description
===========
I'm effectively trying to reproduce the issue in #1322 to test a client and am finding I'm too n00b to create it.
I'm trying to create a Variable with a complex type, but I can't seem to define the nested type nodes without getting a BadTypeMismatch.

Background Information / Reproduction Steps
===========================================
I'm trying to create a variable with structure:
```
myStruct
|-- int32
|-- int64
\-- string
```
with a matching type definition... 
I started from the existing Point type example, and modified it to be more complex, i.e. to try to create children of the top-level type node.
But try as I may, I get BadTypeMismatch when creating the second node, I've also tried creating the second as a VariableTypeNode which doesn't work either (and my interpretation of the spec was that only the top-level was to be a type node, and nested nodes should be VariableNodes...

Can i have a teensy bit of help please?  If I can make it work I'm happy to add as another example in the repo to help future newbies :-)

As an aside, the existing example is a little vague on one point which makes it hard to copy:
```
typedef struct {
    UA_Float x;
    UA_Float y;
    UA_Float z;
} Point;

/* The datatype description for the Point datatype */
#define Point_padding_y offsetof(Point,y) - offsetof(Point,x) - sizeof(UA_Float)
#define Point_padding_z offsetof(Point,z) - offsetof(Point,y) - sizeof(UA_Float)
```
in the above, because the `Point` type has elements of the same type, the padding macro is ambiguous, are we subtracting the sizeof the previous member, or the current member? (i.e. both are `UA_Float` so I can't tell), just a small niggle I found when starting from the examples.

Checklist
=========
Please provide the following information:

 - [up-to-date with git commit 3db5c9bde1c22d7d9de3c2284a89401f6978d084 ] open62541 Version (release number or git tag):
 - [ n/a ] Other OPC UA SDKs used (client or server): 
 - [ ubuntu 16.04 ] Operating system:
 - [[output.log.gz](https://github.com/open62541/open62541/files/1514698/output.log.gz) ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ n/a ] Wireshark network dump attached
 - [ [custom_type_struct_reproduction.tar.gz](https://github.com/open62541/open62541/files/1514621/custom_type_struct_reproduction.tar.gz) ] Self-contained code example attached
 - [ no ] Critical issue

**Comment by WoutvdBerg** [comment] 2017-11-29 19:00
If you just want to test a client: grab the uaCppServer from Unified Automation, it contains a workOrderVariableType with nested variables. 

If you want to know how to add these yourself with open62541 I can't help you.

**Comment by jpfr** [comment] 2017-11-30 08:18
> `#define Point_padding_y offsetof(Point,y) - offsetof(Point,x) - sizeof(UA_Float)`
This computes the padding betwen the members x and y.

There is a difference between defining a structure and defining a variabletype with child variables.
Note that the child variables do not have a particular order in the graph structure of nodes and references.

You probably want a single variabletype node that references your custom structure datatype in the `dataType` field.

**Comment by andreas-ibm** [comment] 2017-11-30 11:31
Ahh, ok, I *think* I understand, I now have the following code: 
[custom_type_struct_reproduction.tar.gz](https://github.com/open62541/open62541/files/1517547/custom_type_struct_reproduction.tar.gz)

which almost works... It has a custom type with a single variabletype node with a DataType field set to myStruct...
Instantiation is:
```
  //Let's make an extension object shall we
  myStruct struct1;
  struct1.intvar=14;
  struct1.dintvar=12345678;
  struct1.stringvar=UA_String_fromChars("wibble");

  UA_VariableAttributes attr2 = UA_VariableAttributes_default;
  UA_Variant_setScalar(&attr2.value, &struct1, &MyStructType);
  attr2.description = UA_LOCALIZEDTEXT("en_US","struct1 Extension Object");
  attr2.displayName = UA_LOCALIZEDTEXT("en_US","struct1");
  attr2.dataType = MyStructType.typeId;

  /* Add the variable node to the information model */
  UA_NodeId myObjectNodeId = UA_NODEID_STRING(1, "struct1");
  UA_QualifiedName myObjectName = UA_QUALIFIEDNAME(1, "struct1");
  UA_NodeId parentNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER);
  UA_NodeId parentReferenceNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES);
  UA_Server_addVariableNode(server,
                            myObjectNodeId,
                            parentNodeId,
                            parentReferenceNodeId,
                            myObjectName,
                            MyStructType.typeId,
                            attr2,
                            NULL,
                            NULL);

  /* Start adding the children */
  UA_VariableAttributes intAttr;
  UA_VariableAttributes_init(&intAttr);
  intAttr.displayName = UA_LOCALIZEDTEXT("en_US", "int32");
  intAttr.dataType = UA_TYPES[UA_TYPES_INT32].typeId;
  intAttr.valueRank = -1;
  UA_NodeId intNodeId = UA_NODEID_STRING(1, "struct1.int32");;
  printf("Adding int32 node with value %d\n", struct1.intvar);
  UA_Variant_setScalar(&intAttr.value, &struct1.intvar, &UA_TYPES[UA_TYPES_INT32]);
  UA_Server_addVariableNode(server,
                            intNodeId,
                            myObjectNodeId,
                            UA_NODEID_NUMERIC(0, UA_NS0ID_HASCOMPONENT),
                            UA_QUALIFIEDNAME(1, "int32"),
                            UA_NODEID_NUMERIC(0, UA_NS0ID_BASEDATAVARIABLETYPE),
                            intAttr,
                            NULL,
                            NULL);
```
The instantiation of the structure in the Object tree has its three sub-components listed in the tree, but alas when i try to read them I get:
`Bad_NotReadable (0x803A0000) "The access level does not allow reading or subscribing to the Node.`
Anything obvious I'm missing?

(Thanks again for looking at this, although I've read large parts of the specification I'm still rather new to OPC_UA)

PS! I tried performing logging by calling the UA_LOG_INFO macro with UA_LOGCATEGORY_USERLAND, but gcc refuses because UA_Server is still a undefined struct, short of #including ua_server_internal, is there a way to invoke the logs "properly", I reverted to printf instead.

**Comment by jpfr** [comment] 2017-11-30 12:24
The logger is defined in the server config.
Just do a `UA_LOG_INFO(config->logger, UA_LOGCATEGORY_USERLAND, "mylog");`
Or include `plugins/ua_log_stdout.h` and use the definition from there.

**Comment by andreas-ibm** [comment] 2017-11-30 12:29
you're right, I'm an idiot, I forgot that I have access to the config var!

**Comment by jpfr** [comment] 2017-11-30 12:29
The basic AccessLevel is set in the variable attributes.
The access control policy in the server can only remove access rights for the specific user. Not add them.

You can do either
```c
intAttr->accessLevel = UA_ACCESSLEVELMASK_READ;
```
or use the default definitions
```c
  UA_VariableAttributes intAttr = UA_VariableAttributes_default;
```

**Comment by andreas-ibm** [comment] 2017-11-30 12:48
Yay, brilliant, all is working well now!
I assumed the (old) _init functions did the same as the _default, turns out that's not the case!

Right, one question before I close, do you want me to upload my completed code to the repository as an example / warning to others?

**Comment by andreas-ibm** [comment] 2017-11-30 12:53
I spoke too soon!
Although my code is "working", it's still different from what the Siemens exposes... On the Siemens PLC uaExpert is able to show the Value of the structure as a full structure, and on my test server it appears simply as "ExtensionObject", so we're clearly doing something different.  I'll diff things in more detail, and grab wireshark logs if necessary!

**Comment by jpfr** [comment] 2017-11-30 13:02
> Right, one question before I close, do you want me to upload my completed code to the repository as an example / warning to others?

Sure! We can add your improvements to the datatypes example.
https://github.com/open62541/open62541/blob/master/examples/custom_datatype/server_types_custom.c
If you want your name to appear in the commit log, you can also send us a Github PR.

> On the Siemens PLC uaExpert is able to show the Value of the structure as a full structure,

The value is encoded as an "ExtensionObject" in any case. In addition, the Siemens server might explain the structure in the datatypes hierarchy.
Somewhere in a "Dictionary" under `/Root/DataTypes/BaseDataType/...`.
We currently don't automatically create this "explanation".
Sorry, this project is WIP. We haven't gotten around to it.

**Comment by WoutvdBerg** [comment] 2017-11-30 13:10
fyi: Siemens has variable types with the variables in it but also nested variables under the variable with a structure styled datatype without the need for the structure datatype. This means there are 2 ways to read/write them.

**Comment by Pro** [comment] 2017-11-30 13:59
I'm not sure if UaExpert also uses the `Opc.Ua` node (i=7617) to decode extension objects. It is more or less the content of the `Opc.Ua.DataTypes.bsd` file. 
That's definitely an open ToDo to properly represent ExtensionObjects in open62541 so that clients (like UaExpert) can decode them.

**Comment by andreas-ibm** [comment] 2017-11-30 14:59
Thanks @WoutvdBerg I think I understand about the two ways; 1. Write a variable by (effectively) sending the updated Bytes and 2. Write a variable by sending updated sub-variables.

@jpfr & @Pro I think my interpretation of your comments are that it's not possible to provide the information that uaExpert uses to represent the ExtensionObject (or is it the case that it's *possible*, but hard?).
My follow-up then, from your experience, *should* a client do what uaExpert is potentially doing and read a dictionary? (and can I confirm what uaExpert is doing; can I directly look at dictionaries from the uaExpert client?)

**Comment by jpfr** [comment] 2017-11-30 16:09
The Siemens PLC is doing nothing secret. Every aspect of its information model can be introspected and replicated in open62541.

The UAExpert is a generic client that constructs some nice GUI elements on the fly.
In 90% of the cases, the client contains some hard-coded logic that acts on the received value.
So they have the structure representation compiled in. See the example in our repository for how to do that client-side.

There is a way to represent the structure layout as a dictionary-object with special child nodes. Probably the UAExpert is using that to generate GUI elements.
See Chapter 5.8 for Part 3 of the OPC UA Spec (can be downloaded from the Foundation's Website with a free registered account). We could generate such a dictionary-object from the `UA_DataType` type description. But we currently don't.

**Comment by jpfr** [comment] 2017-11-30 16:10
> can I directly look at dictionaries from the uaExpert client

Yes. They can be found under the `DataType` node representing the structure.
`Root/Types/DataTypes/BaseDataType/...`

**Comment by andreas-ibm** [comment] 2017-11-30 17:25
Thanks again for the lessons!

I've already downloaded those chapters and have them open both on my computer and on my e-reader for nice bedtime reading...

I'm still not convinced uaExpert is using the dictionary... I can see three different Variables in the Type Tree that is available to it. If I follow things through from the Object tree:
```
Objects
\--Device
   \-- foo
       \--myStruct    [NodeId:ns=3;s="foo"."myStruct", NodeClass:Variable, Value:ExtensionObject, DataType:ns=3;s=DT_"foo"."myStruct"]
          |-HasComponent->element1                                                                                 |                               
          |-HasComponent->element2                                                                                 \                               
          |-HasComponent->element3                                                                                  \
          \-HasTypeDefinition->"foo"."myStruct"-\                                                                    \
                                                 |                                                                    \---------------\
Types                                            |                                                                                     \
|--VariableTypes                                 |                                                                                      \
|  \--BaseVariableType                           |                                                                                       \
|     \--BaseDataVariableType                    /                                                                                       |
|        \--SimaticStructuresType               /                                                                                        |
|           \--"foo"."myStruct"             <--/  [NodeId:ns=3;s=VT_"foo"."myStruct", NodeClass:VariableType, Value:null, DataType:null] |
|              |-HasComponent->element1                                                                                                  |
|              |-HasComponent->element2                                                                                                 /
|              \-HasComponent->element3                                                                                                / 
\--DataTypes                                                                                                                          / 
   |--BaseDataType                                                                                                                   / 
   |  \--Structure                                                                                                                  / 
   |     \--SimaticStructures                                                                                                      / 
   |        \--"foo"."myStruct" [NodeId:ns=3;s=DT_"foo"."myStruct", NodeClass:DataType]   <---------------------------------------/ 
   \--OPC Binary                                                                                                                  
      \--SimaticStructures
         \--"foo"."myStruct"    [NodeId:ns=3;s=TD_"foo"."myStruct", NodeClass:Variable, Value:"foo"."myStruct", DataType:string]
            |-HasTypeDefinition->DataTypeDescriptionType
            \-DescriptionOf->Default Binary             
```
None of these nodes are of type DataTypeDictionaryType as defined by the 5.8.1 in Part 3. I can only assume it's somehow using the HasComponent structure as defined by the DT_"foo"."myStruct" node. (Which was why I was trying to create Variable class nodes as HasComponent children of a VariableType class node, as this is what's in that tree).

OK, I just managed to define a VaribleType with Variable children to "fully" define the structure in the Types.VariableTypes.BaseVariableType.BaseDataVariableType.myStruct node, and still uaExpert is not showing the Value of my structure properly, so it must be doing something magic with that DataType node, even though I can't see anything under that node that describes the structure (I've used both the Prosys and uaExpert clients to browse to see if there's anything either client is hiding from me).

Brain dump over, tomorrow I think I'll try to manually recreate the nodes under Types.DataTypes.BaseDataType.Structure.myStruct!

**Comment by Stasik0** [comment] 2017-11-30 17:28
You can try to use wireshark to find out whether uaexpert is reading the dictionary.

**Comment by andreas-ibm** [comment] 2017-12-01 13:44
Hah, yes, alas I don't have permission to do a tcpdump on that network :-( which is one of the reasons I want a local reproduction!

I've got a step closer now, I have a custom DataType in the Root.Types.DataTypes.BaseDataType.Structure.myStruct, that both the VariableType and the Variable refer to as their DataType, but still no luck with uaExpert, so I'd guess I need an entry in Root.Types.DataTypes.OPC Binary! Any ideas on how to progress that, I seem to have progressed beyond what any examples describe ;-)

**Comment by andreas-ibm** [comment] 2017-12-01 15:27
Ah-hah!
Whilst the Root.Types.DataTypes.OPC Binary.SimaticStructures."foo.Struct" is just a Variable type with no information in it, the Root.Types.DataTypes.OPC Binary.SimaticStructures is a Variable with the full XML TypeDictionary, which I presume is what uaExpert is using. 

Consider me enlightened!

**Comment by WoutvdBerg** [comment] 2017-12-01 15:49
Seems right. Another example without the need for an Siemens PLC: uaCppserver has a variable with datatype Person. Person doesn't have a variable type but has a node in the OPC Binary. UAExpert is able to show the sub-variables from the person datatype.

**Comment by andreas-ibm** [comment] 2017-12-01 15:56
yeah, think that's a Windows program, and I really can't be bothered to spin up a VM to run it right now, maybe if I get desperate ;-)

**Comment by andreas-ibm** [comment] 2017-12-01 17:08
Getting closer, I've created a dictionary (CustomStructures under OPC Binary) and a type definition under OPC Binary, but I need a Type Encoding to map between the Root.Types.DataTypes.BaseDataType.Structure.myStruct and Root.Types.DataTypes.OPC Binary.CustomStructures.myStruct.

This should be a node with a EncodingOf reference to Root.Types.DataTypes.BaseDataType.Structure.myStruct
and a HasDescription reference to
Root.Types.DataTypes.OPC Binary.CustomStructures.myStruct
but I'm not allowed to create it, because neither of these are Hierarchical!

On the Siemens server, this node seems to exist as a dangling node, i.e. I can't find it in the address space, but can get to it by coming from either side!

Any tips?

**Comment by andreas-ibm** [comment] 2017-12-04 13:59
Right, thought I'd created everything, I have a structure with a 
Root.Types.DataTypes.BaseDataType.Structure.myStruct
Root.Types.DataTypes.OPC binary.CustomStructures.myStruct
Root.Types.VariableTypes.BaseVaribleType.BaseDataVariableType.myStruct
with the appropriate references between them and
Root.Objects.struct1 with DataType of myStruct

But still uaExpert refuses to show the value of my object, so I must be missing something.
Can anyone try building and running themselves?
[custom_type_struct_reproduction.tar.gz](https://github.com/open62541/open62541/files/1527320/custom_type_struct_reproduction.tar.gz)
(`gcc -g  -I ../.. server_types_struct.c -o server_types_struct -L../../bin/ -lopen62541`)

I'm now perusing the WireShark logs, but not having a comparison makes it tricky!

**Comment by Stasik0** [comment] 2017-12-05 09:45
@andreas-ibm unfortinately it looks good... I'd propose to download UaAnsiCServer example of unified automation, it has a vector datatype that is working... then I'd try to decode the XML data dictionary it is sending and look into it more precisely
@jpfr could you please fix these two lines
//hassubtype_attr.inverseName = UA_LOCALIZEDTEXT("", "SubtypeOf");
hassubtype_attr.inverseName = UA_LOCALIZEDTEXT("", "HasSupertype");
in NS0 init?

**Comment by andreas-ibm** [comment] 2017-12-05 10:23
It would appear that I failed to create a dictionary in uaExpert's opinion:
From the Siemens server:
```
16:42:15.191Z|4|2318* DONE OpcUa_ClientApi_Browse [ret=0x0,status=0x0]
16:42:15.191Z|6|2318* <-- UaSession::browse [status=0x0]
16:42:15.191Z|7|2318* 3 DataTypeDictionaries found
16:42:15.191Z|7|2318*     Opc.Ua [NodeId = i=7617]
16:42:15.191Z|7|2318*     Opc.Ua.Di [NodeId = ns=2;i=6435]
16:42:15.191Z|7|2318*     SimaticStructures [NodeId = ns=3;i=6001]
16:42:15.191Z|6|2318* --> UaSession::read count=2 [Session=1]
16:42:15.191Z|7|2318* Read 2 nodes
16:42:15.191Z|7|2318*   Node[0] NodeId=ns=2;i=6435 AtrId=13
16:42:15.191Z|7|2318*   Node[1] NodeId=ns=3;i=6001 AtrId=13
16:42:15.191Z|4|2318* CALL OpcUa_ClientApi_Read
```
And from my server:
```
16:49:11.354Z|4|A2E0C700* DONE OpcUa_ClientApi_Browse [ret=0x0,status=0x0]
16:49:11.354Z|6|A2E0C700* <-- UaSession::browse [status=0x0]
16:49:11.354Z|7|A2E0C700* 2 DataTypeDictionaries found
16:49:11.354Z|7|A2E0C700*     Opc.Ua [NodeId = i=7617]
16:49:11.354Z|7|A2E0C700*     CustomStructures [NodeId = ns=1;s=Dict]
16:49:11.354Z|7|A2E0C700* No dictionaries found.
```
So I clearly did something wrong, think I have a little spec-staring to do today. thanks for the help

**Comment by WoutvdBerg** [comment] 2017-12-05 10:29
Probably not but maybe UAExpert uses only numeric identifiers for the dictionaries?

**Comment by jpfr** [comment] 2017-12-05 10:32
@Stasik0 Like this? #1435

**Comment by Stasik0** [comment] 2017-12-05 11:04
Y

**Comment by andreas-ibm** [comment] 2017-12-05 14:15
Is there a particular method I should use to update the NamespaceArray?

**Comment by WoutvdBerg** [comment] 2017-12-08 12:48
In the 1.04 spec part 3 there are changes to the dictionary part. It looks to me like the dictionary part is deleted but may still be used. Maybe this can help.

**Comment by andreas-ibm** [comment] 2017-12-08 13:16
Thanks, I got a little bit closer, managed to get uaExpert to acknowledge the dictionary and the types defined within it (at least i can see it loading them in the log), but it still refuses to actually break down the variable, making me think I'm still missing something.

I'm currently using the uaAnsiCServer, but I'll have to come back to getting this working I fear! And yes it's a little annoying that it'll change for 1.04 (granted it should probably have been done like this in the first case).

"Changes"? that's putting it lightly, there's no mention of the word "dictionary" in the whole document!
"The encoding of the Structured DataType is transmitted with each value", holy bandwidth hog, batman!
Oh jeez, just read the spec, what were they smoking?

**Comment by Stasik0** [comment] 2017-12-08 13:26
What did you change?

**Comment by andreas-ibm** [comment] 2017-12-08 13:33
Let me upload the latest, think it was just a simple change of the DataType of one of the dictionary nodes
[custom_type_struct_reproduction.tar.gz](https://github.com/open62541/open62541/files/1542756/custom_type_struct_reproduction.tar.gz)

**Comment by andreas-ibm** [comment] 2017-12-08 13:34
My assumption was that 1.04 would simply take the individual XML encoding definitions and put them into an attribute, upon reading it appears to be entirely different so I might as well just discard everything I've done for the last two weeks.
*sobs*

**Comment by Stasik0** [comment] 2017-12-08 13:34
Did you manage to decode a "working" dictionary? As xml file?

**Comment by Stasik0** [comment] 2017-12-08 13:38
Is 1.04 not backeard-compatible? Does open62541 need to support it asap?

**Comment by andreas-ibm** [comment] 2017-12-08 13:55
Although the wording I was given was that dictionaries would be "deprecated", but considering they've deleted all mention of them, and only left the old definition in an "Archive", it's a pretty harsh deprecation mechanism. Anyone implementing a server or client from the 1.04 spec would have a very hard time talking to a 1.03 system.
There's a whole bunch of new DataTypes too (fun, fun,fun).

**Comment by WoutvdBerg** [comment] 2017-12-08 14:04
It's still mentioned but not in part 3. It is in part 5 where it is to be backwards compatible.
In the spec they recommend to use the new method: DataTypeDefinition Attribute.

**Comment by Stasik0** [comment] 2017-12-08 14:09
Still, it will take time until it will get int iec.

**Comment by andreas-ibm** [comment] 2017-12-08 14:10
Forgot to answer your previous question.  I *believe* I managed to create a working dictionary, I totally cheated of course, I defined the XML in a separate file and read it at startup, it's not dynamically generated.

**Comment by andreas-ibm** [comment] 2017-12-08 14:23
OK, so I might have overreacted a little. I haven't read the new Part 5, and their site seems a little ill at the moment, will take a look later.

**Comment by WoutvdBerg** [comment] 2017-12-08 14:26
@andreas-ibm, the spec parts have a revision history chapter. In this chapter all tables, images and texts that have changed are mentioned.

**Comment by Stasik0** [comment] 2017-12-08 14:29
I'd appreciate a working example regardless if it is cheated.

**Comment by andreas-ibm** [comment] 2017-12-08 14:38
Example is given in comment above, not sure how to reference, so here's the link again: https://github.com/open62541/open62541/files/1542756/custom_type_struct_reproduction.tar.gz

My plan was (once it's working) to check this into the repo properly

**Comment by Stasik0** [comment] 2017-12-08 14:44
I thought, uaexpert still does break down the variable properly?

**Comment by andreas-ibm** [comment] 2017-12-08 14:53
Indeed, so only partially working; the last step eludes me, I spent far too much time with side-by-side wireshark comparisons

**Comment by Pro** [comment] 2018-02-01 14:40
@andreas-ibm did you manage to get UaExpert showing the ExtensionObject as the corresponding structure?

It would be nice to get this issue solved before the (near) release of 0.3

**Comment by Pro** [comment] 2018-02-01 14:42
Note that this issue is the same as #1420

**Comment by andreas-ibm** [comment] 2018-02-01 15:27
Alas I failed, think my latest attempt is what I uploaded in https://github.com/open62541/open62541/issues/1414#issuecomment-350264071, I switched to using the uaAnsiCpp server in a VM to test our client against (the whole reason was to test whether our client could handle the dictionaries, and I wanted something we could regression test against, which we might still need to revisit).
I don't know how quickly the industry moves, to whether there is real need to support complex types with dictionaries, or wether it's just as well to implement the "new" 1.04 system and ignore the old...
I've been moved on to a different project now, so won't be able to work on this for some time (if ever!), so feel free to close the issue if you so desire.

thanks,
Andreas

**Comment by Pro** [comment] 2018-02-20 14:26
Closing as duplicate of #1420

@andreas-ibm thanks anyways for all your efforts! Maybe someone from the community finds some time to investigate that further

**Closed by Pro** 2018-02-20 14:26 UTC
